import { useEffect, useState, type FormEvent } from "react";
import { pickingApi, type PickingClient, type PickingItem } from "../../lib/api";
const panel="rounded-2xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]";
const input="mt-1 h-12 w-full rounded-lg border border-gray-300 px-3 text-base dark:border-gray-700 dark:bg-gray-900";
const button="inline-flex h-11 items-center justify-center rounded-lg bg-brand-600 px-4 text-sm font-medium text-white disabled:opacity-50";
export default function PickingPage({api=pickingApi}:{api?:PickingClient}){
 const [items,setItems]=useState<PickingItem[]>([]); const [active,setActive]=useState<PickingItem|null>(null); const [progress,setProgress]=useState({picked:0,required:0}); const [error,setError]=useState(""); const [loading,setLoading]=useState(true);
 useEffect(()=>{api.list().then(setItems).catch(()=>setError("Không thể tải danh sách soạn.")).finally(()=>setLoading(false));},[api]);
 async function claim(item:PickingItem){setError("");try{await api.claim(item.id);setActive({...item,status:"picking"});}catch{setError("Phiếu đang được người khác soạn.");}}
 async function scan(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!active)return;const form=event.currentTarget;const data=new FormData(form);try{setProgress(await api.scan(active.id,{locationBarcode:String(data.get("locationBarcode")).trim(),itemBarcode:String(data.get("itemBarcode")).trim()}));form.reset();}catch{setError("Mã vị trí hoặc hàng không khớp FEFO.");}}
 async function confirm(){if(!active)return;try{await api.confirm(active.id);setItems(rows=>rows.filter(row=>row.id!==active.id));setActive(null);}catch{setError("Chưa soạn đủ số lượng.");}}
 if(loading)return <p role="status">Đang tải phiếu soạn…</p>;
 if(active)return <div className="mx-auto max-w-xl space-y-5"><h1 className="text-2xl font-semibold">Soạn {active.documentNo}</h1>{error&&<p role="alert" className="rounded-lg bg-error-50 p-3 text-error-700">{error}</p>}<p aria-label="Tiến độ" className="text-lg font-semibold">{progress.picked} / {progress.required || "?"}</p><form onSubmit={scan} className={`space-y-4 ${panel}`}><label className="block text-sm font-medium">Barcode vị trí<input name="locationBarcode" autoFocus required className={input}/></label><label className="block text-sm font-medium">Barcode sản phẩm / lô / serial<input name="itemBarcode" required className={input}/></label><button className={button}>Lưu lần quét</button></form><button type="button" onClick={confirm} className={button}>Xác nhận đã soạn</button></div>;
 return <div className="space-y-6"><h1 className="text-2xl font-semibold">Phiếu chờ soạn</h1>{error&&<p role="alert">{error}</p>}<section className={panel}><div className="overflow-x-auto"><table className="min-w-full"><thead><tr><th className="px-4 py-3 text-left">Số phiếu</th><th className="px-4 py-3 text-left">Trạng thái</th><th className="px-4 py-3 text-right">Action</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td className="px-4 py-3">{item.documentNo}</td><td className="px-4 py-3">{item.status==="picking"?"Đang soạn":"Chờ soạn"}</td><td className="px-4 py-3 text-right"><button className={button} onClick={()=>claim(item)}>{item.status==="picking"?"Tiếp tục":"Nhận phiếu"}</button></td></tr>)}</tbody></table></div></section></div>;
}
