export const permissionCatalog = {
  "admin.users": ["view", "create", "update", "delete"],
  "admin.roles": ["view", "create", "update", "delete"],
  locations: ["view", "create", "update", "delete"],
  "catalog.categories": ["view", "create", "update", "delete"],
  "catalog.units": ["view", "create", "update", "delete"],
  products: ["view", "create", "update", "delete"],
  partners: ["view", "create", "update", "delete"],
  receipts: ["view", "create", "approve", "print"],
  outbounds: ["view", "create", "approve", "print"],
  picking: ["view", "update", "approve"],
  checking: ["view", "update", "approve"],
  "outbound.exceptions": ["view", "update", "approve"],
  purchasing: ["view", "create", "update", "approve"],
  sales: ["view", "create", "update", "approve"],
  returns: ["view", "create", "approve"],
  stockCounts: ["view", "create", "update", "approve"],
  transfers: ["view", "create", "update", "approve"],
  inventory: ["view", "create"],
  reports: ["view", "export"],
  print: ["print"],
} as const;

type PermissionCatalog = typeof permissionCatalog;
export type PermissionCode = {
  [Feature in keyof PermissionCatalog]: `${Feature}.${PermissionCatalog[Feature][number]}`
}[keyof PermissionCatalog];

export const routePermissionCatalog = {
  "GET /api/admin/users": "admin.users.view",
  "POST /api/admin/users": "admin.users.create",
  "PATCH /api/admin/users/:id": "admin.users.update",
  "POST /api/admin/users/:id/avatar": "admin.users.update",
  "PATCH /api/admin/users/:id/status": "admin.users.delete",
  "PUT /api/admin/users/:id/roles": "admin.users.update",
  "GET /api/admin/roles": "admin.roles.view",
  "POST /api/admin/roles": "admin.roles.create",
  "GET /api/locations": "locations.view",
  "POST /api/locations": "locations.create",
  "GET /api/locations/lookup/:barcode": "locations.view",
  "GET /api/catalog/categories": "catalog.categories.view",
  "POST /api/catalog/categories": "catalog.categories.create",
  "GET /api/catalog/units": "catalog.units.view",
  "POST /api/catalog/units": "catalog.units.create",
  "GET /api/products": "products.view",
  "POST /api/products": "products.create",
  "GET /api/products/lookup/:barcode": "products.view",
  "GET /api/partners": "partners.view",
  "POST /api/partners": "partners.create",
  "PATCH /api/partners/:id": "partners.update",
  "PATCH /api/partners/:id/status": "partners.delete",
  "GET /api/inventory/balances": "inventory.view",
  "GET /api/inventory/lots": "inventory.view",
  "GET /api/inventory/serials": "inventory.view",
  "GET /api/inventory/movements": "inventory.view",
  "GET /api/stock/balances": "inventory.view",
  "POST /api/stock/movements": "inventory.create",
  "GET /api/receipts": "receipts.view",
  "POST /api/receipts": "receipts.create",
  "POST /api/receipts/:id/confirm": "receipts.approve",
  "GET /api/outbounds": "outbounds.view",
  "POST /api/outbounds": "outbounds.create",
  "POST /api/outbounds/:id/release": "outbounds.approve",
  "GET /api/picking": "picking.view",
  "POST /api/picking/:id/claim": "picking.update",
  "POST /api/picking/:id/scan": "picking.update",
  "POST /api/picking/:id/confirm": "picking.approve",
  "GET /api/checking": "checking.view",
  "POST /api/checking/:id/claim": "checking.update",
  "POST /api/checking/:id/scan": "checking.update",
  "POST /api/checking/:id/ship": "checking.approve",
  "GET /api/outbound-exceptions": "outbound.exceptions.view",
  "POST /api/outbound-exceptions/:id/mismatch": "outbound.exceptions.update",
  "POST /api/outbound-exceptions/:id/approve-short": "outbound.exceptions.approve",
  "POST /api/outbound-exceptions/:id/cancel": "outbound.exceptions.approve",
  "POST /api/outbound-exceptions/:id/return-cancel": "outbound.exceptions.approve",
  "POST /api/outbound-exceptions/:id/reassign": "outbound.exceptions.approve",
  "GET /api/purchase-orders": "purchasing.view",
  "POST /api/purchase-orders": "purchasing.create",
  "POST /api/purchase-orders/:id/approve": "purchasing.approve",
  "POST /api/purchase-orders/:id/receive": "purchasing.approve",
  "GET /api/sales": "sales.view",
  "POST /api/sales": "sales.create",
  "POST /api/sales/:id/approve": "sales.approve",
  "POST /api/sales/:id/invoice": "sales.approve",
  "GET /api/returns": "returns.view",
  "POST /api/returns": "returns.create",
  "POST /api/returns/:id/confirm": "returns.approve",
  "GET /api/stock-counts": "stockCounts.view",
  "POST /api/stock-counts": "stockCounts.create",
  "PUT /api/stock-counts/:id/actuals": "stockCounts.update",
  "POST /api/stock-counts/:id/submit": "stockCounts.update",
  "POST /api/stock-counts/:id/approve": "stockCounts.approve",
  "GET /api/transfers": "transfers.view",
  "POST /api/transfers": "transfers.create",
  "POST /api/transfers/:id/dispatch": "transfers.approve",
  "POST /api/transfers/:id/receive": "transfers.approve",
  "POST /api/transfers/:id/cancel": "transfers.update",
  "GET /api/reports/dashboard": "reports.view",
  "GET /api/reports/inventory": "reports.view",
  "GET /api/reports/inventory.csv": "reports.export",
  "GET /api/print/documents/:id": "print.print",
  "GET /api/print/labels/:kind/:id": "print.print",
} as const satisfies Record<string, PermissionCode>;

export const permissionCodes = Object.entries(permissionCatalog).flatMap(
  ([feature, actions]) => actions.map((action) => `${feature}.${action}` as PermissionCode),
);

const permissionCodeSet = new Set<string>(permissionCodes);

export function isPermissionCode(value: string): value is PermissionCode {
  return permissionCodeSet.has(value);
}
